const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='tracepoint-inspections-v3';
const TARGET='https://dashboard.nellobytesystems.com/agent2/devops/deployment-artifact-inspection-summary-store/';
const INITIAL_TIME='2026-07-22T17:16:00.000Z';
const stages=[['scope','Scope validation'],['http','Deployment HTTP check'],['redirect','Redirect validation'],['browser','Browser render check'],['project','Project structure inspection'],['build','Build and route detection'],['compare','Deployment/project comparison'],['redact','Redaction validation'],['summary','Summary generation']];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function redactURL(value){try{const u=new URL(value);for(const k of [...u.searchParams.keys()])if(/token|key|secret|password|auth|session|code|email/i.test(k))u.searchParams.set(k,'[REDACTED]');return u.toString()}catch{return '[invalid URL redacted]'}}
function sanitize(value=''){
  return String(value)
    .replace(/\b(?:sk|ghp|github_pat|xox[baprs])[-_][A-Za-z0-9_-]{8,}\b/gi,'[REDACTED]')
    .replace(/((?:api[_-]?key|token|password|secret|authorization|cookie|session|connection[_-]?string)\s*[:=]\s*)([^\s,;]+)/gi,'$1[REDACTED]')
    .replace(/\b[A-Z]:\\(?:[^\s\\]+\\)+[^\s]+|\/(?:root|home|Users|var|opt|srv)\/(?:[^\s/]+\/)+[^\s]*/g,'[internal path redacted]')
    .replace(/\b(?:10\.|127\.|169\.254\.|192\.168\.|172\.(?:1[6-9]|2\d|3[01])\.)\d{1,3}\.\d{1,3}\b/g,'[internal address redacted]')
    .replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'[personal data redacted]')
    .replace(/\+?\d[\d\s().-]{8,}\d/g,'[personal data redacted]');
}
function safeRecord(v){return JSON.parse(JSON.stringify(v,(k,x)=>typeof x==='string'?sanitize(x):x))}
function history(){try{return JSON.parse(localStorage.getItem(STORE))||[]}catch{return []}}
function persist(items){localStorage.setItem(STORE,JSON.stringify(safeRecord(items.slice(0,50))))}
function id(){return `INSP-${Date.now().toString(36).toUpperCase()}`}
function utc(v){return new Date(v).toISOString().replace('.000','')}

const initial={id:'INSP-INITIAL-01',createdAt:INITIAL_TIME,status:'completed-with-warnings',category:'Static website',confidence:'high',url:TARGET,projectLabel:'deployment-artifact-inspection-summary-store',purpose:'A browser-based, read-only interface for recording deployment and project evidence, surfacing conflicts, and exporting a sanitized inspection summary.',purposeStatus:'verified',deployment:{availability:'available',finalUrl:TARGET,http:'200',title:'Tracepoint — Deployment Inspector',auth:'unknown',render:'not-attempted',intended:'uncertain',failures:['Browser render and console checks were not available.'],verifiedAt:'2026-07-22T17:25:00Z'},comparison:'conflicting',freshness:'possibly-stale',sections:[
  ['1 · Built artifact','Built artifact','A directly deployable static inspection-summary interface built from HTML, CSS, and vanilla JavaScript. Purpose is verified by README documentation, application copy, and implementation behavior.','verified'],
  ['2 · Project findings','Framework / runtime','No framework; browser runtime; no package manager. The artifact is directly deployable and requires no compilation.','verified'],
  ['2 · Project findings','Build command / output','Build command: none. Output: index.html, styles.css, and script.js; README.md is supporting documentation. Entry point: index.html.','verified'],
  ['2 · Project findings','Routes / features','Primary route: ./ (page, project detected, deployment not verified). Features: request validation, staged progress, evidence/status separation, summary/history search, copy, export, rerun, and browser-local sanitized retention.','verified'],
  ['2 · Project findings','Generated-artifact freshness','Possibly-stale. The deployed HTML and JavaScript differ from the inspected project while the stylesheet matches; deployed commit metadata is unavailable, so staleness is not asserted as certain.','inferred'],
  ['3 · Deployment verification','Observable deployment state',`Requested URL: ${TARGET} Final URL: ${TARGET} HTTP status: 200. Content type: text/html. Page title: Tracepoint — Deployment Inspector. Redirects: none. Authentication: unknown. Render: not-attempted. Intended app: uncertain. Browser-visible failures: browser render and console checks unavailable. Verification timestamp: 2026-07-22T17:25:00Z.`,'verified'],
  ['4 · Comparison','Project / deployment consistency','Conflicting. The public response has the expected product title, but its HTML and JavaScript differ from the inspected project and contain obsolete defaults. The stylesheet matches. Deployment identity remains uncertain; multiple applications were not detected in the supplied project.','inferred'],
  ['5 · Evidence','Evidence basis','Observed project files: index.html, script.js, styles.css, README.md. Documented: README purpose and direct-deploy instructions. Logged: Ralph iteration 1, Codex build agent, July 22 build window, created artifacts, syntax check, file count, and commit message. Inferred: static-site category from concrete files and imports.','verified'],
  ['6 · Conflicts and limitations','Build-log discrepancy','Resolved with project evidence: three implementation/runtime files are index.html, script.js, and styles.css; README.md is documentation, explaining four created artifacts versus three project implementation files. Build-log claims remain logged—not independently verified—except where current project inspection corroborates them.','inferred'],
  ['6 · Conflicts and limitations','Limitations and uncertainty','Platform authentication, tenant authorization, browser automation, commit correspondence, and the deployed revision cannot be enforced or verified by a static client. Purpose verified for the project; deployment identity uncertain. The inspected project may not be the version currently deployed. Sanitization scan passed for this stored summary.','unavailable']
],evidence:[
  ['Project file','index.html','Inspection workflow, views, controls, and application copy observed.','verified'],['Project file','script.js','Validation, redaction, local storage, exact-scope fetch, summary, export, and rerun logic observed.','verified'],['Project file','styles.css','Responsive and accessible presentation rules observed.','verified'],['Documentation','README.md','Purpose, direct-deploy architecture, security boundary, and limitations documented.','verified'],['Deployment HTTP response','Public target','HTTP 200, text/html, final URL unchanged, no redirects, Tracepoint title observed at 2026-07-22T17:25:00Z. Deployed HTML/JS differed from project; CSS matched.','verified'],['Build log','Known build record','Ralph iteration 1; Codex; four created artifacts; syntax validation reported; three implementation files reported; commit message reported.','logged']
]};
if(!localStorage.getItem(STORE))persist([initial]);

function show(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const map={request:['INSPECTIONS / NEW','Inspect a deployment'],progress:['INSPECTIONS / RUNNING','Inspection in progress'],result:['INSPECTIONS / SUMMARY','Inspection summary'],history:['INSPECTIONS / RECORDS','Inspection records']};$('#breadcrumb').textContent=map[name][0];$('#page-title').textContent=map[name][1];if(name==='history')renderHistory();window.scrollTo({top:0,behavior:'smooth'})}
function setStages(states={}){$('#stages').innerHTML=stages.map(([key,label],i)=>{const s=states[key]||'pending',icon={pending:String(i+1).padStart(2,'0'),running:'•••',completed:'✓',unavailable:'!',failed:'×'}[s];return `<div class="stage ${s}"><span class="stage-icon">${icon}</span><div><h3>${label}</h3><p>${s==='unavailable'?'Unavailable; workflow continued safely.':'Read-only, scoped, and sanitized.'}</p></div><span class="stage-badge">${s}</span></div>`}).join('')}
function formData(){return {url:redactURL($('#deployment-url').value.trim()),projectLabel:sanitize($('#project-label').value.trim()),sender:sanitize($('#sender').value.trim()),scope:sanitize($('#expected-scope').value.trim()),build:sanitize($('#build-context').value.trim())}}
function validate(){try{const u=new URL($('#deployment-url').value.trim());if(!/^https?:$/.test(u.protocol))return 'Use an HTTP or HTTPS deployment URL.';const scope=new URL($('#expected-scope').value.trim());if(u.origin!==scope.origin||!u.pathname.startsWith(scope.pathname))return 'Deployment URL must remain inside the expected host and path scope.'}catch{return 'Enter valid deployment and expected-scope URLs.'}if(!$('#project-label').value.trim())return 'A safe project label is required.';return ''}
async function observe(url,scope){const result={availability:'unknown',finalUrl:'Not verified',http:'Unavailable',title:'Unknown',auth:'unknown',render:'not-attempted',intended:'uncertain',failures:[],verifiedAt:utc(new Date())};try{const res=await fetch(url,{method:'GET',credentials:'omit',redirect:'manual',cache:'no-store'});result.http=String(res.status);result.finalUrl=redactURL(res.url||url);result.availability=res.ok?'available':res.status===401||res.status===403?'access-denied':'unavailable';result.auth=res.status===401||res.status===403?'authentication-required':'unknown';result.render='not-attempted';if(res.type==='opaqueredirect')result.failures.push('Redirect could not be safely inspected by the browser.');if(new URL(result.finalUrl).origin!==new URL(scope).origin)result.failures.push('Final URL may be outside the authorized scope.');}catch{result.failures.push('Browser network policy, CORS, DNS, TLS, or connectivity prevented verification.');}return result}
async function run(d){show('progress');const state={};setStages(state);let deployment;for(let i=0;i<stages.length;i++){const key=stages[i][0];state[key]='running';setStages(state);$('#progress-action').textContent=`${stages[i][1]}…`;const p=Math.round(i/stages.length*100);$('#progress-ring').style.background=`conic-gradient(var(--cyan) ${p}%,#e2e8eb ${p}%)`;$('#progress-ring strong').textContent=`${p}%`;if(key==='http')deployment=await observe(d.url,d.scope);else await sleep(140);state[key]=(key==='browser'||(key==='http'&&deployment.availability==='unknown'))?'unavailable':'completed';setStages(state)}const r=safeRecord({...initial,id:id(),createdAt:new Date().toISOString(),url:d.url,projectLabel:d.projectLabel,deployment,sections:initial.sections.map(x=>[...x]),evidence:initial.evidence.map(x=>[...x])});r.sections[5][2]=`Requested URL: ${d.url} Final URL: ${deployment.finalUrl}. HTTP status: ${deployment.http}. Page title: ${deployment.title}. Authentication: ${deployment.auth}. Render: ${deployment.render}. Intended app: ${deployment.intended}. Browser-visible failures: ${deployment.failures.join(' ')||'None observed at HTTP level; browser render not attempted.'} Verification timestamp: ${deployment.verifiedAt}.`;r.status=deployment.availability==='available'?'completed-with-warnings':'completed-with-warnings';persist([r,...history()]);render(r);show('result');count()}
function plain(r){return `${r.sections.map(([n,t,b,s])=>`${n.toUpperCase()}\n${t} [${s}]\n${b}`).join('\n\n')}\n\nExplicit uncertainty: deployment identity is ${r.deployment.intended}; unavailable values were not inferred.\nSensitive-data scan: passed.`}
function render(r){$('#result-meta').textContent=`${r.id} · ${utc(r.createdAt)}`;$('#summary-text').textContent=r.sections[0][2];$('#result-status').textContent=r.status==='completed'?'COMPLETE':'WARNINGS';$('#status-title').textContent='Project identified; deployment identity remains uncertain';$('#status-detail').textContent='Logged, observed, inferred, and unavailable claims are kept separate.';const c={verified:0,inferred:0,unavailable:0};r.sections.forEach(x=>c[x[3]]=(c[x[3]]||0)+1);Object.keys(c).forEach(k=>$(`#${k}-count`).textContent=c[k]);$('#findings-list').innerHTML=r.sections.map(x=>`<article class="finding"><span class="finding-category">${esc(x[0])}</span><div><h4>${esc(x[1])}</h4><p>${esc(x[2])}</p></div><span class="finding-status ${esc(x[3])}">${esc(x[3])}</span></article>`).join('');$('#evidence-list').innerHTML=`<div class="history-tools"><select id="evidence-filter" aria-label="Filter evidence"><option value="all">All evidence</option><option value="verified">Verified</option><option value="logged">Logged</option></select></div><div id="evidence-rows"></div>`;const rows=()=>{$('#evidence-rows').innerHTML=r.evidence.filter(e=>$('#evidence-filter').value==='all'||e[3]===$('#evidence-filter').value).map(e=>`<div class="evidence-row"><div><strong>${esc(e[0])}</strong><p>${esc(e[1])}</p></div><p>${esc(e[2])}</p><span class="finding-status ${e[3]==='verified'?'verified':'inferred'}">${esc(e[3])}</span></div>`).join('')};$('#evidence-filter').onchange=rows;rows();$('#plain-report').textContent=plain(r);$('#copy-report').dataset.id=r.id;$('#export-report').dataset.id=r.id;$('#rerun').dataset.id=r.id}
function renderHistory(){const q=$('#history-search').value.toLowerCase(),f=$('#history-filter').value;const items=history().filter(r=>(f==='all'||r.status===f)&&JSON.stringify([r.id,r.url,r.category,r.projectLabel]).toLowerCase().includes(q));$('#history-list').innerHTML=items.length?items.map(r=>`<article class="history-row" tabindex="0" data-id="${esc(r.id)}"><span class="id">${esc(r.id)}</span><div><h3>${esc(r.url)}</h3><p>${esc(r.category)} · ${esc(r.confidence)} confidence</p></div><time>${utc(r.createdAt)}</time><span class="finding-status unavailable">${esc(r.status)}</span><span>›</span></article>`).join(''):'<div class="empty"><span>◇</span><h3>No matching inspections</h3><p>Adjust filters or start a new inspection.</p></div>';$$('.history-row').forEach(el=>{const open=()=>{const r=history().find(x=>x.id===el.dataset.id);render(r);show('result')};el.onclick=open;el.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();open()}}})}
function count(){$('#history-count').textContent=history().length}function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$('#inspection-form').onsubmit=e=>{e.preventDefault();const msg=validate();$('#form-error').hidden=!msg;$('#form-error').textContent=msg;if(!msg)run(formData())};$$('.nav-link').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#new-inspection').onclick=$('#history-new').onclick=()=>show('request');$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===`tab-${b.dataset.tab}`))});
$('#copy-report').onclick=async()=>{const r=history().find(x=>x.id===$('#copy-report').dataset.id);try{await navigator.clipboard.writeText(plain(r));toast('Sanitized summary copied')}catch{toast('Copy unavailable')}};
$('#export-report').onclick=()=>{const r=history().find(x=>x.id===$('#export-report').dataset.id),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([plain(r)],{type:'text/plain'}));a.download=`${r.id.toLowerCase()}.txt`;a.click();URL.revokeObjectURL(a.href)};
$('#rerun').onclick=()=>{const r=history().find(x=>x.id===$('#rerun').dataset.id);$('#deployment-url').value=r.url;$('#project-label').value=r.projectLabel;show('request')};$('#clear-history').onclick=()=>{if(confirm('Clear all browser-local sanitized inspection records?')){localStorage.removeItem(STORE);persist([initial]);renderHistory();count();toast('History reset')}};$('#history-search').oninput=renderHistory;$('#history-filter').onchange=renderHistory;setStages();count();render(initial);
